version: '3.9'

services:
  app:
    image: teslo
    container_name: app-teslo
    build:
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  database:
    image: mongo:5.0.0
    container_name: database-teslo
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
